name: Auto Update Rules

concurrency:
  group: auto-update-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 12 * * *'  # 每天UTC时间12点运行
  workflow_dispatch:      # 手动触发
  push:
    paths:
      - 'source.txt'

jobs:
  process:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      has_changes: ${{ steps.process.outputs.has_changes }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Process rules
        id: process
        run: |
          cd ${{ github.workspace }}
          python scripts/processor.py

      - name: Commit changes
        if: steps.process.outputs.has_changes == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add .
          commit_time=$(date -u +"%Y-%m-%d %H:%M UTC")
          git commit -m "Auto update: $commit_time"
          
          remote_repo="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git pull --rebase $remote_repo main
          git push $remote_repo HEAD:main
