name: Auto Update Rules

concurrency: 
  group: auto-update-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 */8 * * *'  # 每天UTC时间12点运行
  workflow_dispatch:
  push:
    paths:
      - 'source.txt'

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run processor
        run: |
          cd ${{ github.workspace }}
          python scripts/processor.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          
          commit_msg="Auto update: $(date +'%Y-%m-%d %H:%M UTC')"
          remote_repo="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          
          # 强制推送策略
          git pull $remote_repo main
          git add .
          git commit -m "$commit_msg" || echo "No changes to commit"
          git push $remote_repo HEAD:main --force
