name: Auto Update Rules

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'source.txt'

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 使用默认检出路径

      - name: Verify structure
        run: |
          echo "工作目录：$(pwd)"
          ls -l
          echo "source.txt 路径：${{ github.workspace }}/source.txt"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run processor
        run: |
          python scripts/processor.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M UTC')"
          git push
